import {MigrationInterface, QueryRunner} from "typeorm";

export class languages1578581639538 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {

        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(1, 'AB', 'Abkhazian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(2, 'AA', 'Afar')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(3, 'AF', 'Afrikaans')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(4, 'AK', 'Akan')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(5, 'SQ', 'Albanian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(6, 'AM', 'Amharic')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(7, 'AR', 'Arabic')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(8, 'HY', 'Armenian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(9, 'AS', 'Assamese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(10, 'AW', 'Awadhi')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(11, 'AY', 'Aymara')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(12, 'AZ', 'Azerbaijani')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(13, 'BL', 'Balochi')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(14, 'BA', 'Bashkir')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(15, 'EU', 'Basque')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(16, 'BE', 'Belarussian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(17, 'BN', 'Bengali')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(18, 'B1', 'Bhojpuri')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(19, 'DZ', 'Bhutani')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(20, 'BH', 'Bihari')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(21, 'BI', 'Bislama')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(22, 'BR', 'Breton')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(23, 'BG', 'Bulgarian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(24, 'M', 'Burmese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(25, 'CA', 'Catalan')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(26, 'CB', 'Cebuano')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(27, 'CE', 'Chechen')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(28, 'ZH', 'Chinese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(29, 'CO', 'Corsican')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(30, 'HR', 'Croatian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(31, 'CS', 'Czech')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(32, 'DK', 'Dakhini')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(33, 'DA', 'Danish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(34, 'NL', 'Dutch')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(35, 'EN', 'English')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(36, 'EO', 'Esperanto')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(37, 'ET', 'Estonian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(38, 'FO', 'Faeroese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(39, 'FJ', 'Fiji')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(40, 'FI', 'Finnish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(41, 'FR', 'French')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(42, 'FY', 'Frisian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(43, 'GL', 'Galician')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(44, 'KA', 'Georgian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(45, 'DE', 'German')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(46, 'EL', 'Greek')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(47, 'KL', 'Greenlandic')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(48, 'GN', 'Guarani')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(49, 'GU', 'Gujarati')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(50, 'HT', 'Haitian Creole')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(51, 'HA', 'Hausa')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(52, 'IW', 'Hebrew')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(53, 'HI', 'Hindi')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(54, 'HU', 'Hungarian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(55, 'IS', 'Icelandic')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(56, 'IN', 'Indonesian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(57, 'IA', 'Interlingua')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(58, 'IE', 'Interlingue')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(59, 'IK', 'Inupiak')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(60, 'GA', 'Irish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(61, 'IT', 'Italian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(62, 'JA', 'Japanese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(63, 'JW', 'Javanese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(64, 'KB', 'Kabyle')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(65, 'KN', 'Kannada')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(66, 'KS', 'Kashmiri')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(67, 'KK', 'Kazakh')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(68, 'KM', 'Khmer')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(69, 'RW', 'Kinyarwanda')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(70, 'KY', 'Kirghiz')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(71, 'RN', 'Kirundi')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(72, 'KI', 'Konkani')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(73, 'KO', 'Korean')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(74, 'KU', 'Kurdish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(75, 'LO', 'Laothian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(76, 'LA', 'Latin')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(77, 'LV', 'Latvian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(78, 'LN', 'Lingala')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(79, 'LT', 'Lithuanian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(80, 'LM', 'Lombard')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(81, 'LB', 'Luxembourgish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(82, 'MK', 'Macedonian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(83, 'B2', 'Maithili')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(84, 'MU', 'Makhuwa')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(85, 'MG', 'Malagasy')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(86, 'MS', 'Malay')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(87, 'ML', 'Malayalam')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(88, 'MT', 'Maltese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(89, 'MI', 'Maori')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(90, 'MR', 'Marathi')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(91, 'MW', 'Marwari')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(92, 'MO', 'Moldavian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(93, 'MN', 'Mongolian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(94, 'NA', 'Nauru')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(95, 'NE', 'Nepali')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(96, 'NO', 'Norwegian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(97, 'OC', 'Occitan')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(98, 'OR', 'Oriya')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(99, 'OM', 'Oromo')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(100, 'PS', 'Pashto')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(101, 'FA', 'Persian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(102, 'PL', 'Polish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(103, 'PT', 'Portuguese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(104, 'PA', 'Punjabi')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(105, 'QU', 'Quechua')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(106, 'RM', 'Rhaeto-Romance')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(107, 'RI', 'Rifian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(108, 'RO', 'Romanian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(109, 'RU', 'Russian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(110, 'SM', 'Samoan')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(111, 'SG', 'Sangro')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(112, 'SA', 'Sanskrit')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(113, 'GD', 'Scottish Gaelic')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(114, 'SR', 'Serbian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(115, 'SH', 'Serbo-Croatian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(116, 'ST', 'Sesotho')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(117, 'TN', 'Setswana')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(118, 'SN', 'Shona')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(119, 'SD', 'Sindhi')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(120, 'SI', 'Sinhalese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(121, 'SS', 'Siswati')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(122, 'SK', 'Slovak')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(123, 'SL', 'Slovenian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(124, 'SO', 'Somali')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(125, 'ES', 'Spanish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(126, 'SU', 'Sundanese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(127, 'SW', 'Swahili')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(128, 'SV', 'Swedish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(129, 'TL', 'Tagalog')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(130, 'TG', 'Tajik')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(131, 'TZ', 'Tamazight')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(132, 'TA', 'Tamil')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(133, 'TT', 'Tatar')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(134, 'TE', 'Telugu')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(135, 'TH', 'Thai')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(136, 'BO', 'Tibetan')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(137, 'TI', 'Tigrinya')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(138, 'TO', 'Tonga')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(139, 'TS', 'Tsonga')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(140, 'TM', 'Tuareg')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(141, 'TR', 'Turkish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(142, 'TK', 'Turkmen')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(143, 'TW', 'Twi')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(144, 'UK', 'Ukrainian')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(145, 'UR', 'Urdu')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(146, 'UG', 'Uyghur')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(147, 'UZ', 'Uzbek')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(148, 'VI', 'Vietnamese')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(149, 'VO', 'Volapuk')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(150, 'CY', 'Welsh')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(151, 'WO', 'Wolof')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(152, 'XH', 'Xhosa')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(153, 'JI', 'Yiddish')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(154, 'YO', 'Yoruba')`);
        await queryRunner.query(`INSERT INTO "language"(id, code, title) VALUES(155, 'ZU', 'Zulu')`);

        await queryRunner.query(`SELECT setval('language_id_seq', 156)`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {

        await queryRunner.query(`TRUNCATE TABLE "language" CASCADE`);
    }

}
